<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.BuildingBlock.Application</RootNamespace>
    <AssemblyName>SmartEcommerce.BuildingBlock.Application</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../BuildingBlock.Domain/BuildingBlock.Domain.csproj" />
    <ProjectReference Include="../BuildingBlock.Contract/BuildingBlock.Contract.csproj" />
    <ProjectReference Include="..\BuildingBlock.SharedKernel\BuildingBlock.SharedKernel.csproj" />
    <ProjectReference Include="..\BuildingBlock.Criteria\BuildingBlock.Criteria.csproj" />
    <ProjectReference Include="..\BuildingBlock.Messaging\BuildingBlock.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

</Project>
