<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlock.SharedKernel\BuildingBlock.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.BuildingBlock.Domain</RootNamespace>
    <AssemblyName>SmartEcommerce.BuildingBlock.Domain</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
