<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlock.Contract\BuildingBlock.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.70.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="Grpc.HealthCheck" Version="2.70.0" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.BuildingBlock.Grpc</RootNamespace>
    <AssemblyName>SmartEcommerce.BuildingBlock.Grpc</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
