<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlock.Persistence\BuildingBlock.Persistence.csproj" />
    <ProjectReference Include="..\BuildingBlock.Observability\BuildingBlock.Observability.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.BuildingBlock.Persistence.Mongo</RootNamespace>
    <AssemblyName>SmartEcommerce.BuildingBlock.Persistence.Mongo</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    <PackageReference Include="MongoDB.Driver.Core.Extensions.DiagnosticSources" Version="3.0.0" />
  </ItemGroup>

</Project>
