<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.Notification.Application</RootNamespace>
    <AssemblyName>SmartEcommerce.Notification.Application</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Notification.Domain/Notification.Domain.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlock.Application/BuildingBlock.Application.csproj" />
  </ItemGroup>

</Project>
