<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos/auth.proto" GrpcServices="Both" />
    <Protobuf Include="Protos/user.proto" GrpcServices="Both" />
    <Protobuf Include="Protos/inventory.proto" GrpcServices="Both" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.BuildingBlock.Contract</RootNamespace>
    <AssemblyName>SmartEcommerce.BuildingBlock.Contract</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
