<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartEcommerce.Auth.Persistence</RootNamespace>
    <AssemblyName>SmartEcommerce.Auth.Persistence</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auth.Application\Auth.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Domain\BuildingBlock.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks/BuildingBlock.Persistence/BuildingBlock.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks/BuildingBlock.Persistence.Ef/BuildingBlock.Persistence.Ef.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Observability\BuildingBlock.Observability.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

</Project>
