<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="9.0.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Audit.Application/Audit.Application.csproj" />
    <ProjectReference Include="../Audit.Infrastructure/Audit.Infrastructure.csproj" />
    <ProjectReference Include="../Audit.Persistence/Audit.Persistence.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlock.Web/BuildingBlock.Web.csproj" />
  </ItemGroup>

</Project>
